version: "3"
volumes:
  mariadb:
  milvus:
  etcd:
  minio:
networks:
  default:
    name: realchat
services:
  # llama-service:
  #   container_name: llama-service
  #   image: quachhengtony/realchat-services-llama-service:latest
  #   ports:
  #     - 5555:80
  #   restart: unless-stopped
  #   depends_on:
  #     - "mariadb"
  #     - "milvus"
  #     - "sbert"
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realchat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
      - ./Infrastructure/Files:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  sbert:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    container_name: sbert
    restart: unless-stopped
    ports:
      - 9089:8080
    environment:
      ENABLE_CUDA: 0
  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "standalone"]
    restart: unless-stopped
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio:/minio_data
    command: minio server --console-address ":9001" /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
